name: Formatting checks

on:
  workflow_call:

jobs:
  formatting-checks:
    name: Formatting checks
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Run C Format Checks
        run: sh scripts/check_c_formatting.sh
