name: Main

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}@main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  formatting-checks:
    name: Formatting checks
    uses: ./.github/workflows/formatting-checks.yml
    secrets: inherit

  ci-container:
    name: CI container
    uses: ./.github/workflows/ci-container.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  linux:
    name: Build and run Linux targets
    needs: 
      - ci-container
    uses: ./.github/workflows/linux.yml
    secrets: inherit
    with:
      container-tag: ${{ needs.ci-container.outputs.container-tag }}
