name: Main

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}@main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  formatting-checks:
    name: Formatting checks
    uses: ./.github/workflows/formatting-checks.yml
    secrets: inherit
