name: Zephyr

on:
  workflow_call:

jobs:
  build-and-run-zephyr:
    name: Build and Run
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - board: native_sim
            exec: stdbuf -oL -eL timeout 5s bash -c "west build -t run"
          - board: native_sim/native/64
            exec: stdbuf -oL -eL timeout 5s bash -c "west build -t run"
          - board: nrf52840dk/nrf52840
            exec: renode --disable-xwt -e "include @platforms/boards/nrf52840dk_nrf52840.repl; sysbus LoadELF @build/zephyr/zephyr.elf; showAnalyzer uart0; emulation RunFor \"5s\"; start; quit"
    container:
      image: ghcr.io/zephyrproject-rtos/ci@sha256:639a60fb0b381a18ed58628a5996b17aae547d5b2c37d637a7f07a9bd86c511e # v0.29.2
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@5ec39f5cba83346d83a836dfed1524270c660e28 # V1.0.14
        with:
          app-path: .

      - name: Build (application)
        run: west build -p -b ${{ matrix.board }} zephyr/

      - name: Run (application)
        run: |
          EXPECTED_LOG="Hello World"
          echo "info: Running the application"
          ${{ matrix.exec }} | tee zephyr_run.log
          echo "info: Checking for expected log"
          if grep -q "$EXPECTED_LOG" zephyr_run.log; then
            echo "info: Found expected log: $EXPECTED_LOG"
          else
            echo "error: Expected log not found: $EXPECTED_LOG"
            exit 1
          fi
